sudo: required
services:
- docker
script:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- docker build -t thedillonb/github-trending .
- docker push thedillonb/github-trending
env:
  global:
  - secure: nx7Ol0I4nrN6AmxCRpIk8swnONfd6goj0TXb6MZwseMaPlkAv3vaYhUNjVvbCNAMhokH6KbmHZRpsOcUAbbJNlOoI7xkIo/uL6xPIZicExISoawebgU2PHxtVIh32+v/OHt5pOBt8KaetkmTz0HUYg3hJIL05o7cYE7DvetlTCg=
  - secure: E8xUBt7tM0PktreZNCLwfwszi6O7HcO6BB/QZpHRRUIKPOB9eR/bpq2awgdEldxaryJ2Aizg3yDWTw87lNEawMde9ae6p+okoHhURbbTYNfN/Wf5KakrWZL5UtyKu/LoDxoxc9bJs6c7YGSkQYlQqS8PxGVZAd4cN75dhFDOGgo=
